#ifndef GUARD_CONSTANTS_TECHNIQUE_MANUAL_H
#define GUARD_CONSTANTS_TECHNIQUE_MANUAL_H

#include "technique_manual_pages.h"

#define TM_SPECIES_COUNT 5
#define TM_COUNTERS_COUNT 4


enum {
    TM_SPECIESCOUNTER_NONE,
    TM_SPECIESCOUNTER_SEEN,
    TM_SPECIESCOUNTER_COUNT,
};

enum {
    TM_COUNTER_NONE,
    TM_COUNTER_BE_TUTORED,
    TM_COUNTER_SEEN,
    TM_COUNTER_SEEN_RAIN,
    TM_COUNTER_SEEN_SUN,
    TM_COUNTER_WATER_USING_ICE,
    TM_COUNTER_COUNT,
};

#endif
