#ifndef GUARD_CONSTANTS_TECHNIQUE_MANUAL_FLAGS_H
#define GUARD_CONSTANTS_TECHNIQUE_MANUAL_FLAGS_H

enum TmFlags {
    TM_FLAG_CUTTER = 0,
    TM_FLAG_ROXANNE = 1,
    TM_FLAG_FLING_AMULET_COIN = 2,
};

enum TmCounter {
    TM_COUNTER_TACKLE_SEEN = 0,
    TM_COUNTER_POUND_SEEN = 1,
    TM_COUNTER_THUNDER_SEEN = 2,
    TM_COUNTER_THUNDER_SEEN_RAIN = 3,
    TM_COUNTER_SOLAR_BEAM_SEEN = 4,
    TM_COUNTER_SOLAR_BEAM_SEEN_SUN = 5,
    TM_COUNTER_WATER_USING_ICE = 6,
    TM_COUNTER_ACTIVATE_PICKUP = 7,
    TM_COUNTER_FLING_SEEN = 8,
};

enum {
    TM_SPECIES_TACKLE = 0,
    TM_SPECIES_POUND = 3,
    TM_SPECIES_THUNDER = 6,
    TM_SPECIES_SOLAR_BEAM = 9,
    // = 12
};

#endif
