#ifndef GUARD_CONSTANTS_TECHNIQUE_MANUAL_FLAGS_H
#define GUARD_CONSTANTS_TECHNIQUE_MANUAL_FLAGS_H

enum TmFlags {
	TM_FLAG_CUTTER = 0,
	TM_FLAG_ROXANNE = 1,
};

#define TM_COUNTER_WATER_USING_ICE   6

#endif
