#ifndef GUARD_CONSTANTS_TECHNIQUE_MANUAL_PAGES_H
#define GUARD_CONSTANTS_TECHNIQUE_MANUAL_PAGES_H

enum TmPages {
    TM_TACKLE,
    TM_POUND,
    TM_THUNDER,
    TM_SOLAR_BEAM,
    TM_CHILLING_WATER,
    TM_CUT,
    TM_ROCK_TOMB,

    TM_COUNT,
    TM_NONE = 0xFF,
};

#endif
