    [B_TRANSITION_REGIROCK_ORAS] = &Task_RegirockOras,
    [B_TRANSITION_REGICE_ORAS] = &Task_RegiceOras,
    [B_TRANSITION_REGISTEEL_ORAS] = &Task_RegisteelOras,
    [B_TRANSITION_REGIELEKI_ORAS] = &Task_RegielekiOras,
    [B_TRANSITION_REGIDRAGO_ORAS] = &Task_RegidragoOras,
