import os
import sys
import pathlib
import re

HOENN_DEX_PAT = re.compile(r"    HOENN_DEX_(\w+),(?:\s*//.*)?\n")
PREPROC_PAT = re.compile(r"(#(?:if .+|else|endif))\n")

def main(in_filename, out_filename):
    output = [
         "//",
         "// DO NOT MODIFY THIS FILE! It is auto-generated by tools/misc/to_national_order.py",
         "//",
         "",
         "// NOTE: The order of the elements in the array below is irrelevant.",
         "// To reorder the pokedex, see the values in include/constants/pokedex.h.",
         "",
         "#define HOENN_TO_NATIONAL(name)     [HOENN_DEX_##name - 1] = NATIONAL_DEX_##name",
         "",
         "// Assigns all Hoenn Dex Indexes to a National Dex Index",
         "static const enum NationalDexOrder sHoennToNationalOrder[HOENN_DEX_COUNT - 1] =",
         "{",
    ];

    with open(in_filename, "r") as f:
        for line in f.readlines():
            if line == "    HOENN_DEX_NONE,\n":
                pass
            elif line == "    HOENN_DEX_COUNT,\n":
                pass
            elif match := re.match(HOENN_DEX_PAT, line):
                new_line = "    HOENN_TO_NATIONAL(" + match.group(1) + "),"
                output.append(new_line)
            elif match := re.match(PREPROC_PAT, line):
                new_line = match.group(1)
                output.append(new_line)

    output.append("};\n")

    pathlib.Path(out_filename).parent.mkdir(parents=True, exist_ok=True)
    with open(out_filename, "w+") as f:
        f.write('\n'.join(output))

if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
